name: Lint PHP
on:
  push:
    paths:
      - '**.php'
    pull_request:
      types: [ opened, edited, reopened, ready_for_review ]
      paths:
        - '**.php'
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, phpcs

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install PHP Dependencies
        run: composer install --no-progress

      - name: Get changed files
        uses: technote-space/get-diff-action@v3
        with:
          SUFFIX_FILTER: .php

      - name: Detecting PHP Code Standards Violations
        run: vendor/bin/phpcs --colors -s ${{ env.GIT_DIFF }}
        if: "!! env.GIT_DIFF"
