name: Playwright Tests in WordPress Beta

on:
  schedule:
    # Runs "Every Monday 6am UTC"
    - cron: '0 6 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  test:
    name: Run Playwright Beta Only Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: Setup workflow context
        id: workflow
        working-directory: ${{ runner.temp }}
        env:
          REPO: ${{ github.repository }}
        run: |
          mkdir dist
          echo "DIST=${PWD}/dist" >> "$GITHUB_OUTPUT"
          echo "PACKAGE=${REPO##*/}" >> "$GITHUB_OUTPUT"

      - name: Use Node from .nvmrc file
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer vendor directory
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Show versions
        run: |
          php --version
          composer --version
          node --version
          npm --version
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install PHP Dependencies
        run: composer install --no-progress --no-dev --optimize-autoloader --prefer-source

      - name: Setup Registry
        run: printf "\n//npm.pkg.github.com/:_authToken=${{ secrets.NEWFOLD_ACCESS_TOKEN }}" >> .npmrc

      - name: NPM Install
        run: npm install --legacy-peer-deps

      - name: Build JavaScript
        run: npm run build

      - name: Create Distribution Copy
        env:
          DIST: ${{ steps.workflow.outputs.DIST }}
          PACKAGE: ${{ steps.workflow.outputs.PACKAGE }}
        run: rsync -r --include-from=.distinclude --exclude-from=.distignore . "$DIST/$PACKAGE"

      - name: List Distribution Files
        working-directory: ${{ steps.workflow.outputs.DIST }}
        run: find .

      - name: Fetch WordPress beta version and set as output
        id: fetch_beta
        run: |
          WP_BETA_URL=$(curl -s 'https://api.wordpress.org/core/version-check/1.7/?channel=beta' | jq -r '.offers[0].download')
          echo "download_url=$WP_BETA_URL" >> "$GITHUB_OUTPUT"

      - name: Configure WordPress
        env:
          DIST: ${{ steps.workflow.outputs.DIST }}
          PACKAGE: ${{ steps.workflow.outputs.PACKAGE }}
          BETA_ZIP: ${{ steps.fetch_beta.outputs.download_url }}
        run: |
          jq -n \
            --arg core "$BETA_ZIP" \
            --arg plugin "$DIST/$PACKAGE" \
            '{ core: $core, plugins: [$plugin] }' > .wp-env.override.json

      - name: Install WordPress
        run: npx wp-env start --debug

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests
        run: npx playwright test --reporter=line
        env:
          CI: true

      - name: Store Playwright test results
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: playwright-report
          path: tests/playwright/test-results/
          retention-days: 10

      - name: Output debug.log file contents
        if: always()
        continue-on-error: true
        run: |
          npx wp-env run wordpress cat /var/www/html/wp-content/debug.log

      - name: Output wordpress docker logs
        if: always()
        continue-on-error: true
        run: |
          npx wp-env logs --watch=false --debug=true
